# Generated by Django 3.2.13 on 2022-05-28 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', models.ImageField(blank=True, upload_to='')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('content', models.TextField(blank=True)),
                ('music_preview', embed_video.fields.EmbedVideoField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_cover_img', to='blog.release')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_name', to='blog.release')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
